#!/bin/bash
# svn revision: $Id:$

#/**
#  * makedoc - PHPDocumentor script to save your settings
#  * 
#  * Put this file inside your PHP project homedir, edit its variables and run whenever you wants to
#  * re/make your project documentation.
#  * 
#  * The version of this file is the version of PHPDocumentor it is compatible.
#  * 
#  * It simples run phpdoc with the parameters you set in this file.
#  * NOTE: Do not add spaces after bash variables.
#  *
#  * @copyright         makedoc.sh is part of PHPDocumentor project {@link http://freshmeat.net/projects/phpdocu/} and its LGPL
#  * @author            Roberto Berto <darkelder (inside) users (dot) sourceforge (dot) net>
#  * @version           Release-1.1.0
#  */


##############################
# should be edited
##############################

#/**
#  * title of generated documentation, default is 'Generated Documentation'
#  * 
#  * @var               string TITLE
#  */
TITLE="cirrusImage PHP Documentation"

#/** 
#  * name to use for the default package. If not specified, uses 'default'
#  *
#  * @var               string PACKAGES
#  */
PACKAGES="cirrusImage"

#/** 
#  * name of a directory(s) to parse directory1,directory2
#  * $PWD is the directory where makedoc.sh 
#  *
#  * @var               string PATH_PROJECT
#  */
PATH_PROJECT=$PWD

#PROJECT_FILES=/home/forest/NetBeansProjects/net.cirrusimage.api/content/*
PROJECT_FILES=/home/forest/NetBeansProjects/net.cirrusimage.api/content/error,/home/forest/NetBeansProjects/net.cirrusimage.api/content/html,/home/forest/NetBeansProjects/net.cirrusimage.api/content/htmlCollections,/home/forest/NetBeansProjects/net.cirrusimage.api/content/htmlCollectionsFiles,/home/forest/NetBeansProjects/net.cirrusimage.api/content/index,/home/forest/NetBeansProjects/net.cirrusimage.api/content/json,/home/forest/NetBeansProjects/net.cirrusimage.api/content/jsonCollections,/home/forest/NetBeansProjects/net.cirrusimage.api/content/jsonCollectionsFiles,/home/forest/NetBeansProjects/net.cirrusimage.api/content/meta,/home/forest/NetBeansProjects/net.cirrusimage.api/content/thumbnail,/home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtml,/home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtmlCollections,/home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtmlCollectionsFiles
#PROJECT_FILES='--filename /home/forest/NetBeansProjects/net.cirrusimage.api/content/error -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/html -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/htmlCollections -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/htmlCollectionsFiles -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/index -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/json -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/jsonCollections -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/jsonCollectionsFiles -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/meta -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/thumbnail -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtml -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtmlCollections -f /home/forest/NetBeansProjects/net.cirrusimage.api/content/xhtmlCollectionsFiles'

#/**
#  * path of PHPDoc executable
#  *
#  * @var               string PATH_PHPDOC
#  */
PATH_PHPDOC=/usr/bin/phpdoc

#/**
#  * where documentation will be put
#  *
#  * @var               string PATH_DOCS
#  */
PATH_DOCS=$PWD/docs

#/**
#  * what outputformat to use (html/pdf)
#  *
#  * @var               string OUTPUTFORMAT
#  */
OUTPUTFORMAT=HTML

#/** 
#  * converter to be used
#  *
#  * @var               string CONVERTER
#  */
CONVERTER=Smarty

#/**
#  * template to use
#  *
#  * @var               string TEMPLATE
#  */
TEMPLATE=cirrusImage

#/**
#  * parse elements marked as private
#  *
#  * @var               bool (on/off)           PRIVATE
#  */
PRIVATE=off

# make documentation
"$PATH_PHPDOC" -d "$PATH_PROJECT" -f "$PROJECT_FILES" -t "$PATH_DOCS" -ti "$TITLE" -dn $PACKAGES \
-o $OUTPUTFORMAT:$CONVERTER:$TEMPLATE -pp $PRIVATE -s


echo "RewriteEngine Off" | cat > docs/.htaccess


# vim: set expandtab :

